version: "3.9"

services:
  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./backend/src/schema.gql:/backend/src/schema.gql

  codegen-frontend:
    container_name: codegen-frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - ./backend/src/schema.gql:/backend/src/schema.gql
    command: "npm run gen:dev"

  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    depends_on:
      - mongo
    ports:
      - 4001:4001
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    volumes:
      - ./backend:/app

  codegen-backend:
    container_name: codegen-backend
    restart: on-failure
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
    command: "npm run gen:dev"

  mongo:
    image: mongo:5.0.3
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/data/db:/data/db
    command: --quiet --logpath /dev/null

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/shared:/etc/nginx/shared
