version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./backend/src/schema.gql:/backend/src/schema.gql
  
  frontend-codegen:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - ./backend/src/schema.gql:/backend/src/schema.gql
    command: "npx graphql-codegen --watch \"**/*.gql\""

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 4001:4001
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    volumes:
      - ./backend:/app
  
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    volumes:
      - ./volumes/data/db:/data/db
    command: --quiet --logpath /dev/null
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 8080:8080
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/shared:/etc/nginx/shared

