version: "3.9"

services:
  backend:
    image: <repo>/backend:main
    container_name: backend
    depends_on:
      - mongo
    ports:
      - 4001:4001
    volumes:
      - ./volumes/private:/app/private
      - ./volumes/logs:/app/logs
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    env_file:
      - ./backend/private/firebase.env

  mongo:
    image: mongo:5.0.3
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/data/db:/data/db
    command: --quiet --logpath /dev/null

  nginx:
    image: <repo>/proxy:main
    container_name: nginx
    restart: on-failure
    ports:
      - 8080:8080
