scalar Date

type Query {
  version: String!
  items: [Item!]!
}

type Mutation {
  addItem(name: String!): Item
  deleteItem(id: ID!): Boolean
}

type Item {
  id: ID!
  slug: String!
  name: String
  createdDate: Date
}
